apiVersion: v1
kind: Service
metadata:
  labels:
    app: ocs-api
  name: ocs-api
  namespace: default
spec:
  clusterIP: 10.127.243.22
  ports:
  - nodePort: 30379
    port: 80
    protocol: TCP
    targetPort: 9376
  selector:
    app: ocs-api
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ocs-api
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: ocs-api
    spec:
      containers:
      - name: ocs-api
        image: tobyjsullivan/ocs-api:v2
        ports:
        - containerPort: 9376
        env:
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: ocs-api-config
              key: api.host
        - name: PORT
          value: "9376"
        - name: FRONT_END_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: ocs-api-config
              key: front-end.hostname
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: ocs-api-config
              key: aws.region
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            configMapKeyRef:
              name: ocs-api-config
              key: aws.access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: ocs-api-secret
              key: aws.secret-access-key
